server:
  port: 8888
spring:
  config:
    bus:
      destination: springCloudBus
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lotteon2/FLOWERGARDEN.CONFIG.git
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PERSONAL_ACCESS_TOKEN}
management:
  endpoints:
    web:
      exposure:
        include:
          - "refresh"
          - "bus-refresh"