spring:
  kafka:
    bootstrap-servers: localhost:29092
  config:
    activate:
      on-profile: local
encrypt:
  key: ${ENCRYPT_SECRET_KEY}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}